"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.AccountDetailsCardholderViewModel = void 0;
var _ApiClient = require("../ApiClient");
function _typeof(obj) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (obj) { return typeof obj; } : function (obj) { return obj && "function" == typeof Symbol && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }, _typeof(obj); }
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, _toPropertyKey(descriptor.key), descriptor); } }
function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); Object.defineProperty(Constructor, "prototype", { writable: false }); return Constructor; }
function _toPropertyKey(arg) { var key = _toPrimitive(arg, "string"); return _typeof(key) === "symbol" ? key : String(key); }
function _toPrimitive(input, hint) { if (_typeof(input) !== "object" || input === null) return input; var prim = input[Symbol.toPrimitive]; if (prim !== undefined) { var res = prim.call(input, hint || "default"); if (_typeof(res) !== "object") return res; throw new TypeError("@@toPrimitive must return a primitive value."); } return (hint === "string" ? String : Number)(input); } /*
                                                                                                                                                                                                                                                                                                                                                                                               * Finac API
                                                                                                                                                                                                                                                                                                                                                                                               * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * OpenAPI spec version: 2.0
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                               * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * Swagger Codegen version: 3.0.43
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               */
/**
 * The AccountDetailsCardholderViewModel model module.
 * @module model/AccountDetailsCardholderViewModel
 * @version 2.0
 */
var AccountDetailsCardholderViewModel = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>AccountDetailsCardholderViewModel</code>.
   * @alias module:model/AccountDetailsCardholderViewModel
   * @class
   */
  function AccountDetailsCardholderViewModel() {
    _classCallCheck(this, AccountDetailsCardholderViewModel);
  }

  /**
   * Constructs a <code>AccountDetailsCardholderViewModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccountDetailsCardholderViewModel} obj Optional instance to populate.
   * @return {module:model/AccountDetailsCardholderViewModel} The populated <code>AccountDetailsCardholderViewModel</code> instance.
   */
  _createClass(AccountDetailsCardholderViewModel, null, [{
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new AccountDetailsCardholderViewModel();
        if (data.hasOwnProperty('id')) obj.id = _ApiClient.ApiClient.convertToType(data['id'], 'Number');
        if (data.hasOwnProperty('firstName')) obj.firstName = _ApiClient.ApiClient.convertToType(data['firstName'], 'String');
        if (data.hasOwnProperty('middleInitial')) obj.middleInitial = _ApiClient.ApiClient.convertToType(data['middleInitial'], 'String');
        if (data.hasOwnProperty('lastName')) obj.lastName = _ApiClient.ApiClient.convertToType(data['lastName'], 'String');
        if (data.hasOwnProperty('address1')) obj.address1 = _ApiClient.ApiClient.convertToType(data['address1'], 'String');
        if (data.hasOwnProperty('address2')) obj.address2 = _ApiClient.ApiClient.convertToType(data['address2'], 'String');
        if (data.hasOwnProperty('address3')) obj.address3 = _ApiClient.ApiClient.convertToType(data['address3'], 'String');
        if (data.hasOwnProperty('address4')) obj.address4 = _ApiClient.ApiClient.convertToType(data['address4'], 'String');
        if (data.hasOwnProperty('city')) obj.city = _ApiClient.ApiClient.convertToType(data['city'], 'String');
        if (data.hasOwnProperty('state')) obj.state = _ApiClient.ApiClient.convertToType(data['state'], 'String');
        if (data.hasOwnProperty('zip')) obj.zip = _ApiClient.ApiClient.convertToType(data['zip'], 'String');
        if (data.hasOwnProperty('countryCode')) obj.countryCode = _ApiClient.ApiClient.convertToType(data['countryCode'], 'String');
        if (data.hasOwnProperty('countryName')) obj.countryName = _ApiClient.ApiClient.convertToType(data['countryName'], 'String');
        if (data.hasOwnProperty('countyName')) obj.countyName = _ApiClient.ApiClient.convertToType(data['countyName'], 'String');
        if (data.hasOwnProperty('dateOfBirth')) obj.dateOfBirth = _ApiClient.ApiClient.convertToType(data['dateOfBirth'], 'String');
        if (data.hasOwnProperty('phone2')) obj.phone2 = _ApiClient.ApiClient.convertToType(data['phone2'], 'String');
        if (data.hasOwnProperty('userDefined1')) obj.userDefined1 = _ApiClient.ApiClient.convertToType(data['userDefined1'], 'String');
        if (data.hasOwnProperty('userDefined2')) obj.userDefined2 = _ApiClient.ApiClient.convertToType(data['userDefined2'], 'String');
        if (data.hasOwnProperty('userDefined3')) obj.userDefined3 = _ApiClient.ApiClient.convertToType(data['userDefined3'], 'String');
        if (data.hasOwnProperty('userDefined4')) obj.userDefined4 = _ApiClient.ApiClient.convertToType(data['userDefined4'], 'String');
        if (data.hasOwnProperty('kycStatus')) obj.kycStatus = _ApiClient.ApiClient.convertToType(data['kycStatus'], 'String');
      }
      return obj;
    }
  }]);
  return AccountDetailsCardholderViewModel;
}();
/**
 * @member {Number} id
 */
exports.AccountDetailsCardholderViewModel = AccountDetailsCardholderViewModel;
AccountDetailsCardholderViewModel.prototype.id = undefined;

/**
 * @member {String} firstName
 */
AccountDetailsCardholderViewModel.prototype.firstName = undefined;

/**
 * @member {String} middleInitial
 */
AccountDetailsCardholderViewModel.prototype.middleInitial = undefined;

/**
 * @member {String} lastName
 */
AccountDetailsCardholderViewModel.prototype.lastName = undefined;

/**
 * @member {String} address1
 */
AccountDetailsCardholderViewModel.prototype.address1 = undefined;

/**
 * @member {String} address2
 */
AccountDetailsCardholderViewModel.prototype.address2 = undefined;

/**
 * @member {String} address3
 */
AccountDetailsCardholderViewModel.prototype.address3 = undefined;

/**
 * @member {String} address4
 */
AccountDetailsCardholderViewModel.prototype.address4 = undefined;

/**
 * @member {String} city
 */
AccountDetailsCardholderViewModel.prototype.city = undefined;

/**
 * @member {String} state
 */
AccountDetailsCardholderViewModel.prototype.state = undefined;

/**
 * @member {String} zip
 */
AccountDetailsCardholderViewModel.prototype.zip = undefined;

/**
 * @member {String} countryCode
 */
AccountDetailsCardholderViewModel.prototype.countryCode = undefined;

/**
 * @member {String} countryName
 */
AccountDetailsCardholderViewModel.prototype.countryName = undefined;

/**
 * @member {String} countyName
 */
AccountDetailsCardholderViewModel.prototype.countyName = undefined;

/**
 * @member {String} dateOfBirth
 */
AccountDetailsCardholderViewModel.prototype.dateOfBirth = undefined;

/**
 * @member {String} phone2
 */
AccountDetailsCardholderViewModel.prototype.phone2 = undefined;

/**
 * @member {String} userDefined1
 */
AccountDetailsCardholderViewModel.prototype.userDefined1 = undefined;

/**
 * @member {String} userDefined2
 */
AccountDetailsCardholderViewModel.prototype.userDefined2 = undefined;

/**
 * @member {String} userDefined3
 */
AccountDetailsCardholderViewModel.prototype.userDefined3 = undefined;

/**
 * @member {String} userDefined4
 */
AccountDetailsCardholderViewModel.prototype.userDefined4 = undefined;

/**
 * @member {String} kycStatus
 */
AccountDetailsCardholderViewModel.prototype.kycStatus = undefined;