"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.KYCUploadDocumentsBindingModel = void 0;
var _ApiClient = require("../ApiClient");
var _UploadImageBindingModel = require("./UploadImageBindingModel");
function _typeof(obj) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (obj) { return typeof obj; } : function (obj) { return obj && "function" == typeof Symbol && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }, _typeof(obj); }
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, _toPropertyKey(descriptor.key), descriptor); } }
function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); Object.defineProperty(Constructor, "prototype", { writable: false }); return Constructor; }
function _toPropertyKey(arg) { var key = _toPrimitive(arg, "string"); return _typeof(key) === "symbol" ? key : String(key); }
function _toPrimitive(input, hint) { if (_typeof(input) !== "object" || input === null) return input; var prim = input[Symbol.toPrimitive]; if (prim !== undefined) { var res = prim.call(input, hint || "default"); if (_typeof(res) !== "object") return res; throw new TypeError("@@toPrimitive must return a primitive value."); } return (hint === "string" ? String : Number)(input); } /*
                                                                                                                                                                                                                                                                                                                                                                                               * Finac API
                                                                                                                                                                                                                                                                                                                                                                                               * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * OpenAPI spec version: 2.0
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                               * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * Swagger Codegen version: 3.0.43
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               */
/**
 * The KYCUploadDocumentsBindingModel model module.
 * @module model/KYCUploadDocumentsBindingModel
 * @version 2.0
 */
var KYCUploadDocumentsBindingModel = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>KYCUploadDocumentsBindingModel</code>.
   * @alias module:model/KYCUploadDocumentsBindingModel
   * @class
   */
  function KYCUploadDocumentsBindingModel() {
    _classCallCheck(this, KYCUploadDocumentsBindingModel);
  }

  /**
   * Constructs a <code>KYCUploadDocumentsBindingModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/KYCUploadDocumentsBindingModel} obj Optional instance to populate.
   * @return {module:model/KYCUploadDocumentsBindingModel} The populated <code>KYCUploadDocumentsBindingModel</code> instance.
   */
  _createClass(KYCUploadDocumentsBindingModel, null, [{
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new KYCUploadDocumentsBindingModel();
        if (data.hasOwnProperty('id')) obj.id = _ApiClient.ApiClient.convertToType(data['id'], 'String');
        if (data.hasOwnProperty('images')) obj.images = _ApiClient.ApiClient.convertToType(data['images'], [_UploadImageBindingModel.UploadImageBindingModel]);
        if (data.hasOwnProperty('useWebSolution')) obj.useWebSolution = _ApiClient.ApiClient.convertToType(data['useWebSolution'], 'Boolean');
        if (data.hasOwnProperty('mobileNumber')) obj.mobileNumber = _ApiClient.ApiClient.convertToType(data['mobileNumber'], 'String');
        if (data.hasOwnProperty('issuingId')) obj.issuingId = _ApiClient.ApiClient.convertToType(data['issuingId'], 'String');
        if (data.hasOwnProperty('language')) obj.language = _ApiClient.ApiClient.convertToType(data['language'], 'String');
        if (data.hasOwnProperty('successURL')) obj.successURL = _ApiClient.ApiClient.convertToType(data['successURL'], 'String');
        if (data.hasOwnProperty('failureURL')) obj.failureURL = _ApiClient.ApiClient.convertToType(data['failureURL'], 'String');
      }
      return obj;
    }
  }]);
  return KYCUploadDocumentsBindingModel;
}();
/**
 * @member {String} id
 */
exports.KYCUploadDocumentsBindingModel = KYCUploadDocumentsBindingModel;
KYCUploadDocumentsBindingModel.prototype.id = undefined;

/**
 * @member {Array.<module:model/UploadImageBindingModel>} images
 */
KYCUploadDocumentsBindingModel.prototype.images = undefined;

/**
 * @member {Boolean} useWebSolution
 */
KYCUploadDocumentsBindingModel.prototype.useWebSolution = undefined;

/**
 * @member {String} mobileNumber
 */
KYCUploadDocumentsBindingModel.prototype.mobileNumber = undefined;

/**
 * @member {String} issuingId
 */
KYCUploadDocumentsBindingModel.prototype.issuingId = undefined;

/**
 * @member {String} language
 */
KYCUploadDocumentsBindingModel.prototype.language = undefined;

/**
 * @member {String} successURL
 */
KYCUploadDocumentsBindingModel.prototype.successURL = undefined;

/**
 * @member {String} failureURL
 */
KYCUploadDocumentsBindingModel.prototype.failureURL = undefined;