"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.RegisteredDetailsCountBindingModel = void 0;
var _ApiClient = require("../ApiClient");
function _typeof(obj) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (obj) { return typeof obj; } : function (obj) { return obj && "function" == typeof Symbol && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }, _typeof(obj); }
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, _toPropertyKey(descriptor.key), descriptor); } }
function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); Object.defineProperty(Constructor, "prototype", { writable: false }); return Constructor; }
function _toPropertyKey(arg) { var key = _toPrimitive(arg, "string"); return _typeof(key) === "symbol" ? key : String(key); }
function _toPrimitive(input, hint) { if (_typeof(input) !== "object" || input === null) return input; var prim = input[Symbol.toPrimitive]; if (prim !== undefined) { var res = prim.call(input, hint || "default"); if (_typeof(res) !== "object") return res; throw new TypeError("@@toPrimitive must return a primitive value."); } return (hint === "string" ? String : Number)(input); } /*
                                                                                                                                                                                                                                                                                                                                                                                               * Finac API
                                                                                                                                                                                                                                                                                                                                                                                               * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * OpenAPI spec version: 2.0
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                               * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * Swagger Codegen version: 3.0.43
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               */
/**
 * The RegisteredDetailsCountBindingModel model module.
 * @module model/RegisteredDetailsCountBindingModel
 * @version 2.0
 */
var RegisteredDetailsCountBindingModel = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>RegisteredDetailsCountBindingModel</code>.
   * @alias module:model/RegisteredDetailsCountBindingModel
   * @class
   */
  function RegisteredDetailsCountBindingModel() {
    _classCallCheck(this, RegisteredDetailsCountBindingModel);
  }

  /**
   * Constructs a <code>RegisteredDetailsCountBindingModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RegisteredDetailsCountBindingModel} obj Optional instance to populate.
   * @return {module:model/RegisteredDetailsCountBindingModel} The populated <code>RegisteredDetailsCountBindingModel</code> instance.
   */
  _createClass(RegisteredDetailsCountBindingModel, null, [{
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new RegisteredDetailsCountBindingModel();
        if (data.hasOwnProperty('firstName')) obj.firstName = _ApiClient.ApiClient.convertToType(data['firstName'], 'String');
        if (data.hasOwnProperty('lastName')) obj.lastName = _ApiClient.ApiClient.convertToType(data['lastName'], 'String');
        if (data.hasOwnProperty('dateOfBirth')) obj.dateOfBirth = _ApiClient.ApiClient.convertToType(data['dateOfBirth'], 'String');
        if (data.hasOwnProperty('mobile')) obj.mobile = _ApiClient.ApiClient.convertToType(data['mobile'], 'String');
        if (data.hasOwnProperty('phone')) obj.phone = _ApiClient.ApiClient.convertToType(data['phone'], 'String');
        if (data.hasOwnProperty('email')) obj.email = _ApiClient.ApiClient.convertToType(data['email'], 'String');
        if (data.hasOwnProperty('documentNumber')) obj.documentNumber = _ApiClient.ApiClient.convertToType(data['documentNumber'], 'String');
        if (data.hasOwnProperty('documentType')) obj.documentType = _ApiClient.ApiClient.convertToType(data['documentType'], 'String');
        if (data.hasOwnProperty('documentExpiryDate')) obj.documentExpiryDate = _ApiClient.ApiClient.convertToType(data['documentExpiryDate'], 'String');
        if (data.hasOwnProperty('countryOfIssuance')) obj.countryOfIssuance = _ApiClient.ApiClient.convertToType(data['countryOfIssuance'], 'String');
        if (data.hasOwnProperty('address1')) obj.address1 = _ApiClient.ApiClient.convertToType(data['address1'], 'String');
        if (data.hasOwnProperty('address2')) obj.address2 = _ApiClient.ApiClient.convertToType(data['address2'], 'String');
        if (data.hasOwnProperty('zipCode')) obj.zipCode = _ApiClient.ApiClient.convertToType(data['zipCode'], 'String');
        if (data.hasOwnProperty('city')) obj.city = _ApiClient.ApiClient.convertToType(data['city'], 'String');
        if (data.hasOwnProperty('countryCode')) obj.countryCode = _ApiClient.ApiClient.convertToType(data['countryCode'], 'String');
        if (data.hasOwnProperty('bin')) obj.bin = _ApiClient.ApiClient.convertToType(data['bin'], 'String');
        if (data.hasOwnProperty('distributorCode')) obj.distributorCode = _ApiClient.ApiClient.convertToType(data['distributorCode'], 'String');
      }
      return obj;
    }
  }]);
  return RegisteredDetailsCountBindingModel;
}();
/**
 * First name of cardholder.
 * @member {String} firstName
 */
exports.RegisteredDetailsCountBindingModel = RegisteredDetailsCountBindingModel;
RegisteredDetailsCountBindingModel.prototype.firstName = undefined;

/**
 * Last name of cardholder.
 * @member {String} lastName
 */
RegisteredDetailsCountBindingModel.prototype.lastName = undefined;

/**
 * Date of birth of cardholder, in \"yyyy-MM-dd\" format.
 * @member {String} dateOfBirth
 */
RegisteredDetailsCountBindingModel.prototype.dateOfBirth = undefined;

/**
 * Mobile number of cardholder. Mobile number dial code can also be added by separating mobile number and dial code with a |.
 * @member {String} mobile
 */
RegisteredDetailsCountBindingModel.prototype.mobile = undefined;

/**
 * Land line of cardholder. Landline dial code can also be added by separating landline and dial code with a |.
 * @member {String} phone
 */
RegisteredDetailsCountBindingModel.prototype.phone = undefined;

/**
 * Email address of cardholder.
 * @member {String} email
 */
RegisteredDetailsCountBindingModel.prototype.email = undefined;

/**
 * Document number of cardholder.
 * @member {String} documentNumber
 */
RegisteredDetailsCountBindingModel.prototype.documentNumber = undefined;

/**
 * Document type of cardholder.
 * @member {String} documentType
 */
RegisteredDetailsCountBindingModel.prototype.documentType = undefined;

/**
 * Document expiry date of cardholder.
 * @member {String} documentExpiryDate
 */
RegisteredDetailsCountBindingModel.prototype.documentExpiryDate = undefined;

/**
 * Document country of issuance of cardholder in regulation with ISO 3166-1 alpha-2.
 * @member {String} countryOfIssuance
 */
RegisteredDetailsCountBindingModel.prototype.countryOfIssuance = undefined;

/**
 * First line of cardholder address.
 * @member {String} address1
 */
RegisteredDetailsCountBindingModel.prototype.address1 = undefined;

/**
 * Second line of cardholder address.
 * @member {String} address2
 */
RegisteredDetailsCountBindingModel.prototype.address2 = undefined;

/**
 * Post code of cardholder.
 * @member {String} zipCode
 */
RegisteredDetailsCountBindingModel.prototype.zipCode = undefined;

/**
 * City of cardholder address.
 * @member {String} city
 */
RegisteredDetailsCountBindingModel.prototype.city = undefined;

/**
 * Country code of cardholder address.
 * @member {String} countryCode
 */
RegisteredDetailsCountBindingModel.prototype.countryCode = undefined;

/**
 * Assigned by EML. It is the first 8 digits of the cards on your program.
 * @member {String} bin
 */
RegisteredDetailsCountBindingModel.prototype.bin = undefined;

/**
 * The unique identifier assigned by EML, to your program.
 * @member {String} distributorCode
 */
RegisteredDetailsCountBindingModel.prototype.distributorCode = undefined;