/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AccountLoadV2VM} from './AccountLoadV2VM';

/**
 * The AccountLoadsV2VM model module.
 * @module model/AccountLoadsV2VM
 * @version 2.0
 */
export class AccountLoadsV2VM {
  /**
   * Constructs a new <code>AccountLoadsV2VM</code>.
   * @alias module:model/AccountLoadsV2VM
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AccountLoadsV2VM</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccountLoadsV2VM} obj Optional instance to populate.
   * @return {module:model/AccountLoadsV2VM} The populated <code>AccountLoadsV2VM</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AccountLoadsV2VM();
      if (data.hasOwnProperty('daily'))
        obj.daily = AccountLoadV2VM.constructFromObject(data['daily']);
      if (data.hasOwnProperty('monthly'))
        obj.monthly = AccountLoadV2VM.constructFromObject(data['monthly']);
      if (data.hasOwnProperty('yearly'))
        obj.yearly = AccountLoadV2VM.constructFromObject(data['yearly']);
      if (data.hasOwnProperty('lifetime'))
        obj.lifetime = AccountLoadV2VM.constructFromObject(data['lifetime']);
      if (data.hasOwnProperty('dailyCount'))
        obj.dailyCount = AccountLoadV2VM.constructFromObject(data['dailyCount']);
      if (data.hasOwnProperty('monthlyCount'))
        obj.monthlyCount = AccountLoadV2VM.constructFromObject(data['monthlyCount']);
      if (data.hasOwnProperty('yearlyCount'))
        obj.yearlyCount = AccountLoadV2VM.constructFromObject(data['yearlyCount']);
      if (data.hasOwnProperty('lifetimeCount'))
        obj.lifetimeCount = AccountLoadV2VM.constructFromObject(data['lifetimeCount']);
    }
    return obj;
  }
}

/**
 * @member {module:model/AccountLoadV2VM} daily
 */
AccountLoadsV2VM.prototype.daily = undefined;

/**
 * @member {module:model/AccountLoadV2VM} monthly
 */
AccountLoadsV2VM.prototype.monthly = undefined;

/**
 * @member {module:model/AccountLoadV2VM} yearly
 */
AccountLoadsV2VM.prototype.yearly = undefined;

/**
 * @member {module:model/AccountLoadV2VM} lifetime
 */
AccountLoadsV2VM.prototype.lifetime = undefined;

/**
 * @member {module:model/AccountLoadV2VM} dailyCount
 */
AccountLoadsV2VM.prototype.dailyCount = undefined;

/**
 * @member {module:model/AccountLoadV2VM} monthlyCount
 */
AccountLoadsV2VM.prototype.monthlyCount = undefined;

/**
 * @member {module:model/AccountLoadV2VM} yearlyCount
 */
AccountLoadsV2VM.prototype.yearlyCount = undefined;

/**
 * @member {module:model/AccountLoadV2VM} lifetimeCount
 */
AccountLoadsV2VM.prototype.lifetimeCount = undefined;

