/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.43
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CardLoadsV2VM model module.
 * @module model/CardLoadsV2VM
 * @version 2.0
 */
export class CardLoadsV2VM {
  /**
   * Constructs a new <code>CardLoadsV2VM</code>.
   * @alias module:model/CardLoadsV2VM
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CardLoadsV2VM</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CardLoadsV2VM} obj Optional instance to populate.
   * @return {module:model/CardLoadsV2VM} The populated <code>CardLoadsV2VM</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CardLoadsV2VM();
      if (data.hasOwnProperty('loadTriesAsToday'))
        obj.loadTriesAsToday = ApiClient.convertToType(data['loadTriesAsToday'], 'Number');
      if (data.hasOwnProperty('monthlyLoadTries'))
        obj.monthlyLoadTries = ApiClient.convertToType(data['monthlyLoadTries'], 'Number');
      if (data.hasOwnProperty('yearlyLoadTries'))
        obj.yearlyLoadTries = ApiClient.convertToType(data['yearlyLoadTries'], 'Number');
      if (data.hasOwnProperty('totalLoadTries'))
        obj.totalLoadTries = ApiClient.convertToType(data['totalLoadTries'], 'Number');
      if (data.hasOwnProperty('loadAmountAsToday'))
        obj.loadAmountAsToday = ApiClient.convertToType(data['loadAmountAsToday'], 'Number');
      if (data.hasOwnProperty('totalLoad'))
        obj.totalLoad = ApiClient.convertToType(data['totalLoad'], 'Number');
      if (data.hasOwnProperty('monthlyLoad'))
        obj.monthlyLoad = ApiClient.convertToType(data['monthlyLoad'], 'Number');
      if (data.hasOwnProperty('quarterlyLoad'))
        obj.quarterlyLoad = ApiClient.convertToType(data['quarterlyLoad'], 'Number');
      if (data.hasOwnProperty('yearlyLoad'))
        obj.yearlyLoad = ApiClient.convertToType(data['yearlyLoad'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} loadTriesAsToday
 */
CardLoadsV2VM.prototype.loadTriesAsToday = undefined;

/**
 * @member {Number} monthlyLoadTries
 */
CardLoadsV2VM.prototype.monthlyLoadTries = undefined;

/**
 * @member {Number} yearlyLoadTries
 */
CardLoadsV2VM.prototype.yearlyLoadTries = undefined;

/**
 * @member {Number} totalLoadTries
 */
CardLoadsV2VM.prototype.totalLoadTries = undefined;

/**
 * @member {Number} loadAmountAsToday
 */
CardLoadsV2VM.prototype.loadAmountAsToday = undefined;

/**
 * @member {Number} totalLoad
 */
CardLoadsV2VM.prototype.totalLoad = undefined;

/**
 * @member {Number} monthlyLoad
 */
CardLoadsV2VM.prototype.monthlyLoad = undefined;

/**
 * @member {Number} quarterlyLoad
 */
CardLoadsV2VM.prototype.quarterlyLoad = undefined;

/**
 * @member {Number} yearlyLoad
 */
CardLoadsV2VM.prototype.yearlyLoad = undefined;

