/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ConditionConfiguration} from './ConditionConfiguration';

/**
 * The ConditionGroup model module.
 * @module model/ConditionGroup
 * @version 2.0
 */
export class ConditionGroup {
  /**
   * Constructs a new <code>ConditionGroup</code>.
   * @alias module:model/ConditionGroup
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ConditionGroup</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ConditionGroup} obj Optional instance to populate.
   * @return {module:model/ConditionGroup} The populated <code>ConditionGroup</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ConditionGroup();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('bin'))
        obj.bin = ApiClient.convertToType(data['bin'], 'String');
      if (data.hasOwnProperty('dc'))
        obj.dc = ApiClient.convertToType(data['dc'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('configurations'))
        obj.configurations = ApiClient.convertToType(data['configurations'], [ConditionConfiguration]);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ConditionGroup.prototype.id = undefined;

/**
 * @member {String} bin
 */
ConditionGroup.prototype.bin = undefined;

/**
 * @member {String} dc
 */
ConditionGroup.prototype.dc = undefined;

/**
 * @member {String} name
 */
ConditionGroup.prototype.name = undefined;

/**
 * @member {Array.<module:model/ConditionConfiguration>} configurations
 */
ConditionGroup.prototype.configurations = undefined;

