/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateAccountPurseViewModel model module.
 * @module model/CreateAccountPurseViewModel
 * @version 2.0
 */
export class CreateAccountPurseViewModel {
  /**
   * Constructs a new <code>CreateAccountPurseViewModel</code>.
   * @alias module:model/CreateAccountPurseViewModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CreateAccountPurseViewModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateAccountPurseViewModel} obj Optional instance to populate.
   * @return {module:model/CreateAccountPurseViewModel} The populated <code>CreateAccountPurseViewModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateAccountPurseViewModel();
      if (data.hasOwnProperty('m2AccountPurse'))
        obj.m2AccountPurse = ApiClient.convertToType(data['m2AccountPurse'], 'String');
      if (data.hasOwnProperty('accountPurseNumber'))
        obj.accountPurseNumber = ApiClient.convertToType(data['accountPurseNumber'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} m2AccountPurse
 */
CreateAccountPurseViewModel.prototype.m2AccountPurse = undefined;

/**
 * @member {String} accountPurseNumber
 */
CreateAccountPurseViewModel.prototype.accountPurseNumber = undefined;

