/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.43
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Device model module.
 * @module model/Device
 * @version 2.0
 */
export class Device {
  /**
   * Constructs a new <code>Device</code>.
   * @alias module:model/Device
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Device</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Device} obj Optional instance to populate.
   * @return {module:model/Device} The populated <code>Device</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Device();
      if (data.hasOwnProperty('deviceId'))
        obj.deviceId = ApiClient.convertToType(data['deviceId'], 'String');
      if (data.hasOwnProperty('deviceName'))
        obj.deviceName = ApiClient.convertToType(data['deviceName'], 'String');
      if (data.hasOwnProperty('deviceType'))
        obj.deviceType = ApiClient.convertToType(data['deviceType'], 'String');
      if (data.hasOwnProperty('secureElementId'))
        obj.secureElementId = ApiClient.convertToType(data['secureElementId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} deviceId
 */
Device.prototype.deviceId = undefined;

/**
 * @member {String} deviceName
 */
Device.prototype.deviceName = undefined;

/**
 * @member {String} deviceType
 */
Device.prototype.deviceType = undefined;

/**
 * @member {String} secureElementId
 */
Device.prototype.secureElementId = undefined;

