/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CardSpendV2ViewModelItem} from './CardSpendV2ViewModelItem';

/**
 * The GetSpendsV2ViewModel model module.
 * @module model/GetSpendsV2ViewModel
 * @version 2.0
 */
export class GetSpendsV2ViewModel {
  /**
   * Constructs a new <code>GetSpendsV2ViewModel</code>.
   * @alias module:model/GetSpendsV2ViewModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetSpendsV2ViewModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetSpendsV2ViewModel} obj Optional instance to populate.
   * @return {module:model/GetSpendsV2ViewModel} The populated <code>GetSpendsV2ViewModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetSpendsV2ViewModel();
      if (data.hasOwnProperty('daily'))
        obj.daily = CardSpendV2ViewModelItem.constructFromObject(data['daily']);
      if (data.hasOwnProperty('monthly'))
        obj.monthly = CardSpendV2ViewModelItem.constructFromObject(data['monthly']);
      if (data.hasOwnProperty('yearly'))
        obj.yearly = CardSpendV2ViewModelItem.constructFromObject(data['yearly']);
      if (data.hasOwnProperty('lifetime'))
        obj.lifetime = CardSpendV2ViewModelItem.constructFromObject(data['lifetime']);
    }
    return obj;
  }
}

/**
 * @member {module:model/CardSpendV2ViewModelItem} daily
 */
GetSpendsV2ViewModel.prototype.daily = undefined;

/**
 * @member {module:model/CardSpendV2ViewModelItem} monthly
 */
GetSpendsV2ViewModel.prototype.monthly = undefined;

/**
 * @member {module:model/CardSpendV2ViewModelItem} yearly
 */
GetSpendsV2ViewModel.prototype.yearly = undefined;

/**
 * @member {module:model/CardSpendV2ViewModelItem} lifetime
 */
GetSpendsV2ViewModel.prototype.lifetime = undefined;

