/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.43
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetToggleIbanVM model module.
 * @module model/GetToggleIbanVM
 * @version 2.0
 */
export class GetToggleIbanVM {
  /**
   * Constructs a new <code>GetToggleIbanVM</code>.
   * @alias module:model/GetToggleIbanVM
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetToggleIbanVM</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetToggleIbanVM} obj Optional instance to populate.
   * @return {module:model/GetToggleIbanVM} The populated <code>GetToggleIbanVM</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetToggleIbanVM();
      if (data.hasOwnProperty('iban'))
        obj.iban = ApiClient.convertToType(data['iban'], 'String');
      if (data.hasOwnProperty('toggle'))
        obj.toggle = ApiClient.convertToType(data['toggle'], 'Boolean');
      if (data.hasOwnProperty('updatedOn'))
        obj.updatedOn = ApiClient.convertToType(data['updatedOn'], 'String');
      if (data.hasOwnProperty('expiryDate'))
        obj.expiryDate = ApiClient.convertToType(data['expiryDate'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} iban
 */
GetToggleIbanVM.prototype.iban = undefined;

/**
 * @member {Boolean} toggle
 */
GetToggleIbanVM.prototype.toggle = undefined;

/**
 * @member {String} updatedOn
 */
GetToggleIbanVM.prototype.updatedOn = undefined;

/**
 * @member {Date} expiryDate
 */
GetToggleIbanVM.prototype.expiryDate = undefined;

