/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.43
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The LoadLimitsBindingModel model module.
 * @module model/LoadLimitsBindingModel
 * @version 2.0
 */
export class LoadLimitsBindingModel {
  /**
   * Constructs a new <code>LoadLimitsBindingModel</code>.
   * @alias module:model/LoadLimitsBindingModel
   * @class
   * @param bin {String} The first 8 digits of the cards on your program.
   * @param dc {String} The unique identifier assigned by PFS, to your program
   * @param cardType {String} Card Type
   * @param productType {String} Product Type
   */
  constructor(bin, dc, cardType, productType) {
    this.bin = bin;
    this.dc = dc;
    this.cardType = cardType;
    this.productType = productType;
  }

  /**
   * Constructs a <code>LoadLimitsBindingModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoadLimitsBindingModel} obj Optional instance to populate.
   * @return {module:model/LoadLimitsBindingModel} The populated <code>LoadLimitsBindingModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LoadLimitsBindingModel();
      if (data.hasOwnProperty('bin'))
        obj.bin = ApiClient.convertToType(data['bin'], 'String');
      if (data.hasOwnProperty('dc'))
        obj.dc = ApiClient.convertToType(data['dc'], 'String');
      if (data.hasOwnProperty('cardType'))
        obj.cardType = ApiClient.convertToType(data['cardType'], 'String');
      if (data.hasOwnProperty('productType'))
        obj.productType = ApiClient.convertToType(data['productType'], 'String');
    }
    return obj;
  }
}

/**
 * The first 8 digits of the cards on your program.
 * @member {String} bin
 */
LoadLimitsBindingModel.prototype.bin = undefined;

/**
 * The unique identifier assigned by PFS, to your program
 * @member {String} dc
 */
LoadLimitsBindingModel.prototype.dc = undefined;

/**
 * Card Type
 * @member {String} cardType
 */
LoadLimitsBindingModel.prototype.cardType = undefined;

/**
 * Product Type
 * @member {String} productType
 */
LoadLimitsBindingModel.prototype.productType = undefined;

