/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RegisterClientBindingModel model module.
 * @module model/RegisterClientBindingModel
 * @version 2.0
 */
export class RegisterClientBindingModel {
  /**
   * Constructs a new <code>RegisterClientBindingModel</code>.
   * @alias module:model/RegisterClientBindingModel
   * @class
   * @param username {String} 
   * @param password {String} 
   */
  constructor(username, password) {
    this.username = username;
    this.password = password;
  }

  /**
   * Constructs a <code>RegisterClientBindingModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RegisterClientBindingModel} obj Optional instance to populate.
   * @return {module:model/RegisterClientBindingModel} The populated <code>RegisterClientBindingModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RegisterClientBindingModel();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
RegisterClientBindingModel.prototype.name = undefined;

/**
 * @member {String} username
 */
RegisterClientBindingModel.prototype.username = undefined;

/**
 * @member {String} password
 */
RegisterClientBindingModel.prototype.password = undefined;

