/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.43
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {LoadLimitViewModel} from './LoadLimitViewModel';
import {MccLimitViewModel} from './MccLimitViewModel';
import {RegionalLimitViewModel} from './RegionalLimitViewModel';

/**
 * The SpendControlEcmLimits model module.
 * @module model/SpendControlEcmLimits
 * @version 2.0
 */
export class SpendControlEcmLimits {
  /**
   * Constructs a new <code>SpendControlEcmLimits</code>.
   * @alias module:model/SpendControlEcmLimits
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SpendControlEcmLimits</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SpendControlEcmLimits} obj Optional instance to populate.
   * @return {module:model/SpendControlEcmLimits} The populated <code>SpendControlEcmLimits</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SpendControlEcmLimits();
      if (data.hasOwnProperty('load'))
        obj.load = LoadLimitViewModel.constructFromObject(data['load']);
      if (data.hasOwnProperty('atm'))
        obj.atm = RegionalLimitViewModel.constructFromObject(data['atm']);
      if (data.hasOwnProperty('pos'))
        obj.pos = RegionalLimitViewModel.constructFromObject(data['pos']);
      if (data.hasOwnProperty('eCommerce'))
        obj.eCommerce = RegionalLimitViewModel.constructFromObject(data['eCommerce']);
      if (data.hasOwnProperty('moto'))
        obj.moto = RegionalLimitViewModel.constructFromObject(data['moto']);
      if (data.hasOwnProperty('mcc'))
        obj.mcc = ApiClient.convertToType(data['mcc'], [MccLimitViewModel]);
    }
    return obj;
  }
}

/**
 * @member {module:model/LoadLimitViewModel} load
 */
SpendControlEcmLimits.prototype.load = undefined;

/**
 * @member {module:model/RegionalLimitViewModel} atm
 */
SpendControlEcmLimits.prototype.atm = undefined;

/**
 * @member {module:model/RegionalLimitViewModel} pos
 */
SpendControlEcmLimits.prototype.pos = undefined;

/**
 * @member {module:model/RegionalLimitViewModel} eCommerce
 */
SpendControlEcmLimits.prototype.eCommerce = undefined;

/**
 * @member {module:model/RegionalLimitViewModel} moto
 */
SpendControlEcmLimits.prototype.moto = undefined;

/**
 * @member {Array.<module:model/MccLimitViewModel>} mcc
 */
SpendControlEcmLimits.prototype.mcc = undefined;

