/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.43
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TokenSearchBindingModel model module.
 * @module model/TokenSearchBindingModel
 * @version 2.0
 */
export class TokenSearchBindingModel {
  /**
   * Constructs a new <code>TokenSearchBindingModel</code>.
   * @alias module:model/TokenSearchBindingModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TokenSearchBindingModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TokenSearchBindingModel} obj Optional instance to populate.
   * @return {module:model/TokenSearchBindingModel} The populated <code>TokenSearchBindingModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TokenSearchBindingModel();
      if (data.hasOwnProperty('accountPan'))
        obj.accountPan = ApiClient.convertToType(data['accountPan'], 'String');
      if (data.hasOwnProperty('tokenUniqueReference'))
        obj.tokenUniqueReference = ApiClient.convertToType(data['tokenUniqueReference'], 'String');
    }
    return obj;
  }
}

/**
 * When present, the search will return tokens for the Account matching this Primary Account Number (PAN), for any Wallet Provider or device. PAN will be minimum 9 digits and maximum 19 digits. Cannot be used together with any of the following search request parameters:TokenUniqueReference, Token, PaymentAppInstanceId, CommentId, or AlternateAccountIdentifier.  Example: 5412345678901234
 * @member {String} accountPan
 */
TokenSearchBindingModel.prototype.accountPan = undefined;

/**
 * A unique reference assigned following the allocation of a token used to identify the token for the duration of its lifetime. When present, the search will return one specific matching token. The TUR field will be a 48 char string. Cannot be used together with any of the following search request parameters: AccountPan, Token, PaymentAppInstanceId, CommentId, or AlternateAccountIdentifier.  Example: DWSPMC00000000010906a349d9ca4eb1a4d53e3c90a11d9c
 * @member {String} tokenUniqueReference
 */
TokenSearchBindingModel.prototype.tokenUniqueReference = undefined;

