/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.43
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UpdateSecurityDetailsThreeDSBindingModel model module.
 * @module model/UpdateSecurityDetailsThreeDSBindingModel
 * @version 2.0
 */
export class UpdateSecurityDetailsThreeDSBindingModel {
  /**
   * Constructs a new <code>UpdateSecurityDetailsThreeDSBindingModel</code>.
   * @alias module:model/UpdateSecurityDetailsThreeDSBindingModel
   * @class
   * @param securityAnswer {String} Cardholder security answer.
   */
  constructor(securityAnswer) {
    this.securityAnswer = securityAnswer;
  }

  /**
   * Constructs a <code>UpdateSecurityDetailsThreeDSBindingModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateSecurityDetailsThreeDSBindingModel} obj Optional instance to populate.
   * @return {module:model/UpdateSecurityDetailsThreeDSBindingModel} The populated <code>UpdateSecurityDetailsThreeDSBindingModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateSecurityDetailsThreeDSBindingModel();
      if (data.hasOwnProperty('securityQuestion'))
        obj.securityQuestion = ApiClient.convertToType(data['securityQuestion'], 'String');
      if (data.hasOwnProperty('securityAnswer'))
        obj.securityAnswer = ApiClient.convertToType(data['securityAnswer'], 'String');
    }
    return obj;
  }
}

/**
 * Cardholder security question.
 * @member {String} securityQuestion
 */
UpdateSecurityDetailsThreeDSBindingModel.prototype.securityQuestion = undefined;

/**
 * Cardholder security answer.
 * @member {String} securityAnswer
 */
UpdateSecurityDetailsThreeDSBindingModel.prototype.securityAnswer = undefined;

