/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UpdateMandateBindingModel model module.
 * @module model/UpdateMandateBindingModel
 * @version 2.0
 */
export class UpdateMandateBindingModel {
  /**
   * Constructs a new <code>UpdateMandateBindingModel</code>.
   * @alias module:model/UpdateMandateBindingModel
   * @class
   * @param mandateId {Number} Mandate id to be updated
   * @param merchantName {String} Creditor merchant name
   * @param debitingIBAN {String} Debiting cardholder Iban
   * @param statusId {Number} Status id of mandate (1 - Pending, 2 - Blocked, 3 - Cancelled, 4 - Expired)
   * @param mandateUsername {String} Username updating mandate
   */
  constructor(mandateId, merchantName, debitingIBAN, statusId, mandateUsername) {
    this.mandateId = mandateId;
    this.merchantName = merchantName;
    this.debitingIBAN = debitingIBAN;
    this.statusId = statusId;
    this.mandateUsername = mandateUsername;
  }

  /**
   * Constructs a <code>UpdateMandateBindingModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateMandateBindingModel} obj Optional instance to populate.
   * @return {module:model/UpdateMandateBindingModel} The populated <code>UpdateMandateBindingModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateMandateBindingModel();
      if (data.hasOwnProperty('mandateId'))
        obj.mandateId = ApiClient.convertToType(data['mandateId'], 'Number');
      if (data.hasOwnProperty('merchantName'))
        obj.merchantName = ApiClient.convertToType(data['merchantName'], 'String');
      if (data.hasOwnProperty('debitingIBAN'))
        obj.debitingIBAN = ApiClient.convertToType(data['debitingIBAN'], 'String');
      if (data.hasOwnProperty('statusId'))
        obj.statusId = ApiClient.convertToType(data['statusId'], 'Number');
      if (data.hasOwnProperty('mandateUsername'))
        obj.mandateUsername = ApiClient.convertToType(data['mandateUsername'], 'String');
      if (data.hasOwnProperty('referenceNumber'))
        obj.referenceNumber = ApiClient.convertToType(data['referenceNumber'], 'String');
      if (data.hasOwnProperty('reason'))
        obj.reason = ApiClient.convertToType(data['reason'], 'String');
    }
    return obj;
  }
}

/**
 * Mandate id to be updated
 * @member {Number} mandateId
 */
UpdateMandateBindingModel.prototype.mandateId = undefined;

/**
 * Creditor merchant name
 * @member {String} merchantName
 */
UpdateMandateBindingModel.prototype.merchantName = undefined;

/**
 * Debiting cardholder Iban
 * @member {String} debitingIBAN
 */
UpdateMandateBindingModel.prototype.debitingIBAN = undefined;

/**
 * Status id of mandate (1 - Pending, 2 - Blocked, 3 - Cancelled, 4 - Expired)
 * @member {Number} statusId
 */
UpdateMandateBindingModel.prototype.statusId = undefined;

/**
 * Username updating mandate
 * @member {String} mandateUsername
 */
UpdateMandateBindingModel.prototype.mandateUsername = undefined;

/**
 * Merchant reference
 * @member {String} referenceNumber
 */
UpdateMandateBindingModel.prototype.referenceNumber = undefined;

/**
 * @member {String} reason
 */
UpdateMandateBindingModel.prototype.reason = undefined;

