/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ValidateLoginBindingModel model module.
 * @module model/ValidateLoginBindingModel
 * @version 2.0
 */
export class ValidateLoginBindingModel {
  /**
   * Constructs a new <code>ValidateLoginBindingModel</code>.
   * @alias module:model/ValidateLoginBindingModel
   * @class
   * @param password {String} Password
   */
  constructor(password) {
    this.password = password;
  }

  /**
   * Constructs a <code>ValidateLoginBindingModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ValidateLoginBindingModel} obj Optional instance to populate.
   * @return {module:model/ValidateLoginBindingModel} The populated <code>ValidateLoginBindingModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ValidateLoginBindingModel();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
    }
    return obj;
  }
}

/**
 * Cardholder Id
 * @member {String} id
 */
ValidateLoginBindingModel.prototype.id = undefined;

/**
 * Email address
 * @member {String} email
 */
ValidateLoginBindingModel.prototype.email = undefined;

/**
 * Password
 * @member {String} password
 */
ValidateLoginBindingModel.prototype.password = undefined;

/**
 * Username
 * @member {String} username
 */
ValidateLoginBindingModel.prototype.username = undefined;

