/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FinacApi);
  }
}(this, function(expect, FinacApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AdjustmentBindingModelV2', function() {
      beforeEach(function() {
        instance = new FinacApi.AdjustmentBindingModelV2();
      });

      it('should create an instance of AdjustmentBindingModelV2', function() {
        // TODO: update the code to test AdjustmentBindingModelV2
        expect(instance).to.be.a(FinacApi.AdjustmentBindingModelV2);
      });

      it('should have the property amount (base name: "amount")', function() {
        // TODO: update the code to test the property amount
        expect(instance).to.have.property('amount');
        // expect(instance.amount).to.be(expectedValueLiteral);
      });

      it('should have the property fee (base name: "fee")', function() {
        // TODO: update the code to test the property fee
        expect(instance).to.have.property('fee');
        // expect(instance.fee).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property currencyCode (base name: "currencyCode")', function() {
        // TODO: update the code to test the property currencyCode
        expect(instance).to.have.property('currencyCode');
        // expect(instance.currencyCode).to.be(expectedValueLiteral);
      });

      it('should have the property settlementCurrencyCode (base name: "settlementCurrencyCode")', function() {
        // TODO: update the code to test the property settlementCurrencyCode
        expect(instance).to.have.property('settlementCurrencyCode');
        // expect(instance.settlementCurrencyCode).to.be(expectedValueLiteral);
      });

      it('should have the property affectedBalance (base name: "affectedBalance")', function() {
        // TODO: update the code to test the property affectedBalance
        expect(instance).to.have.property('affectedBalance');
        // expect(instance.affectedBalance).to.be(expectedValueLiteral);
      });

    });
  });

}));
