/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FinacApi);
  }
}(this, function(expect, FinacApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AvailableProductTypeViewModel', function() {
      beforeEach(function() {
        instance = new FinacApi.AvailableProductTypeViewModel();
      });

      it('should create an instance of AvailableProductTypeViewModel', function() {
        // TODO: update the code to test AvailableProductTypeViewModel
        expect(instance).to.be.a(FinacApi.AvailableProductTypeViewModel);
      });

      it('should have the property productType (base name: "productType")', function() {
        // TODO: update the code to test the property productType
        expect(instance).to.have.property('productType');
        // expect(instance.productType).to.be(expectedValueLiteral);
      });

      it('should have the property displayName (base name: "displayName")', function() {
        // TODO: update the code to test the property displayName
        expect(instance).to.have.property('displayName');
        // expect(instance.displayName).to.be(expectedValueLiteral);
      });

      it('should have the property mappedTo (base name: "mappedTo")', function() {
        // TODO: update the code to test the property mappedTo
        expect(instance).to.have.property('mappedTo');
        // expect(instance.mappedTo).to.be(expectedValueLiteral);
      });

      it('should have the property kycType (base name: "kycType")', function() {
        // TODO: update the code to test the property kycType
        expect(instance).to.have.property('kycType');
        // expect(instance.kycType).to.be(expectedValueLiteral);
      });

      it('should have the property kycId (base name: "kycId")', function() {
        // TODO: update the code to test the property kycId
        expect(instance).to.have.property('kycId');
        // expect(instance.kycId).to.be(expectedValueLiteral);
      });

      it('should have the property yearlyLoadLimit (base name: "yearlyLoadLimit")', function() {
        // TODO: update the code to test the property yearlyLoadLimit
        expect(instance).to.have.property('yearlyLoadLimit');
        // expect(instance.yearlyLoadLimit).to.be(expectedValueLiteral);
      });

    });
  });

}));
