/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FinacApi);
  }
}(this, function(expect, FinacApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ConditionGroupInsertBindingModel', function() {
      beforeEach(function() {
        instance = new FinacApi.ConditionGroupInsertBindingModel();
      });

      it('should create an instance of ConditionGroupInsertBindingModel', function() {
        // TODO: update the code to test ConditionGroupInsertBindingModel
        expect(instance).to.be.a(FinacApi.ConditionGroupInsertBindingModel);
      });

      it('should have the property bin (base name: "bin")', function() {
        // TODO: update the code to test the property bin
        expect(instance).to.have.property('bin');
        // expect(instance.bin).to.be(expectedValueLiteral);
      });

      it('should have the property dc (base name: "dc")', function() {
        // TODO: update the code to test the property dc
        expect(instance).to.have.property('dc');
        // expect(instance.dc).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property configurations (base name: "configurations")', function() {
        // TODO: update the code to test the property configurations
        expect(instance).to.have.property('configurations');
        // expect(instance.configurations).to.be(expectedValueLiteral);
      });

    });
  });

}));
