/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FinacApi);
  }
}(this, function(expect, FinacApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DDTransactionV2VM', function() {
      beforeEach(function() {
        instance = new FinacApi.DDTransactionV2VM();
      });

      it('should create an instance of DDTransactionV2VM', function() {
        // TODO: update the code to test DDTransactionV2VM
        expect(instance).to.be.a(FinacApi.DDTransactionV2VM);
      });

      it('should have the property endToEndId (base name: "endToEndId")', function() {
        // TODO: update the code to test the property endToEndId
        expect(instance).to.have.property('endToEndId');
        // expect(instance.endToEndId).to.be(expectedValueLiteral);
      });

      it('should have the property instructionId (base name: "instructionId")', function() {
        // TODO: update the code to test the property instructionId
        expect(instance).to.have.property('instructionId');
        // expect(instance.instructionId).to.be(expectedValueLiteral);
      });

      it('should have the property transactionId (base name: "transactionId")', function() {
        // TODO: update the code to test the property transactionId
        expect(instance).to.have.property('transactionId');
        // expect(instance.transactionId).to.be(expectedValueLiteral);
      });

      it('should have the property mandate (base name: "mandate")', function() {
        // TODO: update the code to test the property mandate
        expect(instance).to.have.property('mandate');
        // expect(instance.mandate).to.be(expectedValueLiteral);
      });

      it('should have the property mandateId (base name: "mandateId")', function() {
        // TODO: update the code to test the property mandateId
        expect(instance).to.have.property('mandateId');
        // expect(instance.mandateId).to.be(expectedValueLiteral);
      });

      it('should have the property dateOfSignature (base name: "dateOfSignature")', function() {
        // TODO: update the code to test the property dateOfSignature
        expect(instance).to.have.property('dateOfSignature');
        // expect(instance.dateOfSignature).to.be(expectedValueLiteral);
      });

      it('should have the property amount (base name: "amount")', function() {
        // TODO: update the code to test the property amount
        expect(instance).to.have.property('amount');
        // expect(instance.amount).to.be(expectedValueLiteral);
      });

      it('should have the property requiredDateTime (base name: "requiredDateTime")', function() {
        // TODO: update the code to test the property requiredDateTime
        expect(instance).to.have.property('requiredDateTime');
        // expect(instance.requiredDateTime).to.be(expectedValueLiteral);
      });

      it('should have the property reference (base name: "reference")', function() {
        // TODO: update the code to test the property reference
        expect(instance).to.have.property('reference');
        // expect(instance.reference).to.be(expectedValueLiteral);
      });

      it('should have the property debtorFullName (base name: "debtorFullName")', function() {
        // TODO: update the code to test the property debtorFullName
        expect(instance).to.have.property('debtorFullName');
        // expect(instance.debtorFullName).to.be(expectedValueLiteral);
      });

      it('should have the property debtorIban (base name: "debtorIban")', function() {
        // TODO: update the code to test the property debtorIban
        expect(instance).to.have.property('debtorIban');
        // expect(instance.debtorIban).to.be(expectedValueLiteral);
      });

      it('should have the property debtorBic (base name: "debtorBic")', function() {
        // TODO: update the code to test the property debtorBic
        expect(instance).to.have.property('debtorBic');
        // expect(instance.debtorBic).to.be(expectedValueLiteral);
      });

      it('should have the property debtorPostalAddress (base name: "debtorPostalAddress")', function() {
        // TODO: update the code to test the property debtorPostalAddress
        expect(instance).to.have.property('debtorPostalAddress');
        // expect(instance.debtorPostalAddress).to.be(expectedValueLiteral);
      });

      it('should have the property debtorCountry (base name: "debtorCountry")', function() {
        // TODO: update the code to test the property debtorCountry
        expect(instance).to.have.property('debtorCountry');
        // expect(instance.debtorCountry).to.be(expectedValueLiteral);
      });

      it('should have the property creditorFullName (base name: "creditorFullName")', function() {
        // TODO: update the code to test the property creditorFullName
        expect(instance).to.have.property('creditorFullName');
        // expect(instance.creditorFullName).to.be(expectedValueLiteral);
      });

      it('should have the property creditorIban (base name: "creditorIban")', function() {
        // TODO: update the code to test the property creditorIban
        expect(instance).to.have.property('creditorIban');
        // expect(instance.creditorIban).to.be(expectedValueLiteral);
      });

      it('should have the property creditorBic (base name: "creditorBic")', function() {
        // TODO: update the code to test the property creditorBic
        expect(instance).to.have.property('creditorBic');
        // expect(instance.creditorBic).to.be(expectedValueLiteral);
      });

      it('should have the property creditorPostalAddress (base name: "creditorPostalAddress")', function() {
        // TODO: update the code to test the property creditorPostalAddress
        expect(instance).to.have.property('creditorPostalAddress');
        // expect(instance.creditorPostalAddress).to.be(expectedValueLiteral);
      });

      it('should have the property creditorCountry (base name: "creditorCountry")', function() {
        // TODO: update the code to test the property creditorCountry
        expect(instance).to.have.property('creditorCountry');
        // expect(instance.creditorCountry).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property errorCode (base name: "errorCode")', function() {
        // TODO: update the code to test the property errorCode
        expect(instance).to.have.property('errorCode');
        // expect(instance.errorCode).to.be(expectedValueLiteral);
      });

      it('should have the property incomingOutgoing (base name: "incomingOutgoing")', function() {
        // TODO: update the code to test the property incomingOutgoing
        expect(instance).to.have.property('incomingOutgoing');
        // expect(instance.incomingOutgoing).to.be(expectedValueLiteral);
      });

      it('should have the property statusFlag (base name: "statusFlag")', function() {
        // TODO: update the code to test the property statusFlag
        expect(instance).to.have.property('statusFlag');
        // expect(instance.statusFlag).to.be(expectedValueLiteral);
      });

    });
  });

}));
