/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FinacApi);
  }
}(this, function(expect, FinacApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetRegistrationRuleViewModel', function() {
      beforeEach(function() {
        instance = new FinacApi.GetRegistrationRuleViewModel();
      });

      it('should create an instance of GetRegistrationRuleViewModel', function() {
        // TODO: update the code to test GetRegistrationRuleViewModel
        expect(instance).to.be.a(FinacApi.GetRegistrationRuleViewModel);
      });

      it('should have the property userRegistrationRuleId (base name: "userRegistrationRuleId")', function() {
        // TODO: update the code to test the property userRegistrationRuleId
        expect(instance).to.have.property('userRegistrationRuleId');
        // expect(instance.userRegistrationRuleId).to.be(expectedValueLiteral);
      });

      it('should have the property binDistributorCodeId (base name: "binDistributorCodeId")', function() {
        // TODO: update the code to test the property binDistributorCodeId
        expect(instance).to.have.property('binDistributorCodeId');
        // expect(instance.binDistributorCodeId).to.be(expectedValueLiteral);
      });

      it('should have the property firstName (base name: "firstName")', function() {
        // TODO: update the code to test the property firstName
        expect(instance).to.have.property('firstName');
        // expect(instance.firstName).to.be(expectedValueLiteral);
      });

      it('should have the property lastName (base name: "lastName")', function() {
        // TODO: update the code to test the property lastName
        expect(instance).to.have.property('lastName');
        // expect(instance.lastName).to.be(expectedValueLiteral);
      });

      it('should have the property dateOfBirth (base name: "dateOfBirth")', function() {
        // TODO: update the code to test the property dateOfBirth
        expect(instance).to.have.property('dateOfBirth');
        // expect(instance.dateOfBirth).to.be(expectedValueLiteral);
      });

      it('should have the property mobileNo (base name: "mobileNo")', function() {
        // TODO: update the code to test the property mobileNo
        expect(instance).to.have.property('mobileNo');
        // expect(instance.mobileNo).to.be(expectedValueLiteral);
      });

      it('should have the property phoneNo (base name: "phoneNo")', function() {
        // TODO: update the code to test the property phoneNo
        expect(instance).to.have.property('phoneNo');
        // expect(instance.phoneNo).to.be(expectedValueLiteral);
      });

      it('should have the property email (base name: "email")', function() {
        // TODO: update the code to test the property email
        expect(instance).to.have.property('email');
        // expect(instance.email).to.be(expectedValueLiteral);
      });

      it('should have the property documentNumber (base name: "documentNumber")', function() {
        // TODO: update the code to test the property documentNumber
        expect(instance).to.have.property('documentNumber');
        // expect(instance.documentNumber).to.be(expectedValueLiteral);
      });

      it('should have the property documentType (base name: "documentType")', function() {
        // TODO: update the code to test the property documentType
        expect(instance).to.have.property('documentType');
        // expect(instance.documentType).to.be(expectedValueLiteral);
      });

      it('should have the property countryOfIssuance (base name: "countryOfIssuance")', function() {
        // TODO: update the code to test the property countryOfIssuance
        expect(instance).to.have.property('countryOfIssuance');
        // expect(instance.countryOfIssuance).to.be(expectedValueLiteral);
      });

      it('should have the property address1 (base name: "address1")', function() {
        // TODO: update the code to test the property address1
        expect(instance).to.have.property('address1');
        // expect(instance.address1).to.be(expectedValueLiteral);
      });

      it('should have the property address2 (base name: "address2")', function() {
        // TODO: update the code to test the property address2
        expect(instance).to.have.property('address2');
        // expect(instance.address2).to.be(expectedValueLiteral);
      });

      it('should have the property address3 (base name: "address3")', function() {
        // TODO: update the code to test the property address3
        expect(instance).to.have.property('address3');
        // expect(instance.address3).to.be(expectedValueLiteral);
      });

      it('should have the property address4 (base name: "address4")', function() {
        // TODO: update the code to test the property address4
        expect(instance).to.have.property('address4');
        // expect(instance.address4).to.be(expectedValueLiteral);
      });

      it('should have the property zipCode (base name: "zipCode")', function() {
        // TODO: update the code to test the property zipCode
        expect(instance).to.have.property('zipCode');
        // expect(instance.zipCode).to.be(expectedValueLiteral);
      });

      it('should have the property city (base name: "city")', function() {
        // TODO: update the code to test the property city
        expect(instance).to.have.property('city');
        // expect(instance.city).to.be(expectedValueLiteral);
      });

      it('should have the property countryCode (base name: "countryCode")', function() {
        // TODO: update the code to test the property countryCode
        expect(instance).to.have.property('countryCode');
        // expect(instance.countryCode).to.be(expectedValueLiteral);
      });

      it('should have the property isBlacklisted (base name: "isBlacklisted")', function() {
        // TODO: update the code to test the property isBlacklisted
        expect(instance).to.have.property('isBlacklisted');
        // expect(instance.isBlacklisted).to.be(expectedValueLiteral);
      });

      it('should have the property csrId (base name: "csrId")', function() {
        // TODO: update the code to test the property csrId
        expect(instance).to.have.property('csrId');
        // expect(instance.csrId).to.be(expectedValueLiteral);
      });

      it('should have the property note (base name: "note")', function() {
        // TODO: update the code to test the property note
        expect(instance).to.have.property('note');
        // expect(instance.note).to.be(expectedValueLiteral);
      });

      it('should have the property blockType (base name: "blockType")', function() {
        // TODO: update the code to test the property blockType
        expect(instance).to.have.property('blockType');
        // expect(instance.blockType).to.be(expectedValueLiteral);
      });

      it('should have the property blockExpiryDate (base name: "blockExpiryDate")', function() {
        // TODO: update the code to test the property blockExpiryDate
        expect(instance).to.have.property('blockExpiryDate');
        // expect(instance.blockExpiryDate).to.be(expectedValueLiteral);
      });

      it('should have the property origin (base name: "origin")', function() {
        // TODO: update the code to test the property origin
        expect(instance).to.have.property('origin');
        // expect(instance.origin).to.be(expectedValueLiteral);
      });

      it('should have the property reason (base name: "reason")', function() {
        // TODO: update the code to test the property reason
        expect(instance).to.have.property('reason');
        // expect(instance.reason).to.be(expectedValueLiteral);
      });

      it('should have the property isArchived (base name: "isArchived")', function() {
        // TODO: update the code to test the property isArchived
        expect(instance).to.have.property('isArchived');
        // expect(instance.isArchived).to.be(expectedValueLiteral);
      });

      it('should have the property createdDateTime (base name: "createdDateTime")', function() {
        // TODO: update the code to test the property createdDateTime
        expect(instance).to.have.property('createdDateTime');
        // expect(instance.createdDateTime).to.be(expectedValueLiteral);
      });

      it('should have the property deletedDateTime (base name: "deletedDateTime")', function() {
        // TODO: update the code to test the property deletedDateTime
        expect(instance).to.have.property('deletedDateTime');
        // expect(instance.deletedDateTime).to.be(expectedValueLiteral);
      });

      it('should have the property deletedByCSRId (base name: "deletedByCSRId")', function() {
        // TODO: update the code to test the property deletedByCSRId
        expect(instance).to.have.property('deletedByCSRId');
        // expect(instance.deletedByCSRId).to.be(expectedValueLiteral);
      });

    });
  });

}));
