/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FinacApi);
  }
}(this, function(expect, FinacApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('RegionalLimitViewModel', function() {
      beforeEach(function() {
        instance = new FinacApi.RegionalLimitViewModel();
      });

      it('should create an instance of RegionalLimitViewModel', function() {
        // TODO: update the code to test RegionalLimitViewModel
        expect(instance).to.be.a(FinacApi.RegionalLimitViewModel);
      });

      it('should have the property domestic (base name: "domestic")', function() {
        // TODO: update the code to test the property domestic
        expect(instance).to.have.property('domestic');
        // expect(instance.domestic).to.be(expectedValueLiteral);
      });

      it('should have the property intranational (base name: "intranational")', function() {
        // TODO: update the code to test the property intranational
        expect(instance).to.have.property('intranational');
        // expect(instance.intranational).to.be(expectedValueLiteral);
      });

      it('should have the property international (base name: "international")', function() {
        // TODO: update the code to test the property international
        expect(instance).to.have.property('international');
        // expect(instance.international).to.be(expectedValueLiteral);
      });

      it('should have the property globally (base name: "globally")', function() {
        // TODO: update the code to test the property globally
        expect(instance).to.have.property('globally');
        // expect(instance.globally).to.be(expectedValueLiteral);
      });

    });
  });

}));
