/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FinacApi);
  }
}(this, function(expect, FinacApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FinacApi.BankPaymentApi();
  });

  describe('(package)', function() {
    describe('BankPaymentApi', function() {
      describe('apiBankPaymentDeliveryDateGet', function() {
        it('should call apiBankPaymentDeliveryDateGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiBankPaymentDeliveryDateGet call and complete the assertions
          /*
          var opts = {};

          instance.apiBankPaymentDeliveryDateGet(apiVersion, authorization, fMessageId, fOrigin, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FinacApi.BankPaymentDeliveryDateViewModelValidResponsePackage);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiBankPaymentGetMT103Get', function() {
        it('should call apiBankPaymentGetMT103Get successfully', function(done) {
          // TODO: uncomment, update parameter values for apiBankPaymentGetMT103Get call and complete the assertions
          /*
          var opts = {};

          instance.apiBankPaymentGetMT103Get(apiVersion, authorization, fMessageId, fOrigin, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FinacApi.GetMT103ViewModelValidResponsePackage);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiBankPaymentIdCancelRecurringPatch', function() {
        it('should call apiBankPaymentIdCancelRecurringPatch successfully', function(done) {
          // TODO: uncomment, update parameter values for apiBankPaymentIdCancelRecurringPatch call and complete the assertions
          /*
          var opts = {};

          instance.apiBankPaymentIdCancelRecurringPatch(id, apiVersion, authorization, fMessageId, fOrigin, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FinacApi.BankPaymentCancelRecurringViewModelValidResponsePackage);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiBankPaymentIdOneOffPaymentPost', function() {
        it('should call apiBankPaymentIdOneOffPaymentPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiBankPaymentIdOneOffPaymentPost call and complete the assertions
          /*
          var opts = {};

          instance.apiBankPaymentIdOneOffPaymentPost(id, apiVersion, authorization, fMessageId, fOrigin, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FinacApi.BankPaymentViewModelValidResponsePackage);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiBankPaymentIdRecurringPaymentsGet', function() {
        it('should call apiBankPaymentIdRecurringPaymentsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiBankPaymentIdRecurringPaymentsGet call and complete the assertions
          /*

          instance.apiBankPaymentIdRecurringPaymentsGet(id, apiVersion, authorization, fMessageId, fOrigin, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FinacApi.BankPaymentGetRecurringPaymentsViewModelV2ValidResponsePackage);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiBankPaymentIdRecurringPost', function() {
        it('should call apiBankPaymentIdRecurringPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiBankPaymentIdRecurringPost call and complete the assertions
          /*
          var opts = {};

          instance.apiBankPaymentIdRecurringPost(id, apiVersion, authorization, fMessageId, fOrigin, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FinacApi.BankPaymentRecurringViewModelValidResponsePackage);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiBankPaymentIdStatementByIdGet', function() {
        it('should call apiBankPaymentIdStatementByIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiBankPaymentIdStatementByIdGet call and complete the assertions
          /*
          var opts = {};

          instance.apiBankPaymentIdStatementByIdGet(id, apiVersion, authorization, fMessageId, fOrigin, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FinacApi.BankPaymentStatementByIdViewModelV2ValidResponsePackage);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiBankPaymentIdStatementGet', function() {
        it('should call apiBankPaymentIdStatementGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiBankPaymentIdStatementGet call and complete the assertions
          /*
          var opts = {};

          instance.apiBankPaymentIdStatementGet(id, apiVersion, authorization, fMessageId, fOrigin, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FinacApi.BankPaymentStatementViewModelV2ValidResponsePackage);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiBankPaymentIdUpdatePatch', function() {
        it('should call apiBankPaymentIdUpdatePatch successfully', function(done) {
          // TODO: uncomment, update parameter values for apiBankPaymentIdUpdatePatch call and complete the assertions
          /*
          var opts = {};

          instance.apiBankPaymentIdUpdatePatch(id, apiVersion, authorization, fMessageId, fOrigin, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FinacApi.BankPaymentUpdateViewModelValidResponsePackage);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiBankPaymentParametersGet', function() {
        it('should call apiBankPaymentParametersGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiBankPaymentParametersGet call and complete the assertions
          /*
          var opts = {};

          instance.apiBankPaymentParametersGet(apiVersion, authorization, fMessageId, fOrigin, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FinacApi.BankPaymentParametersViewModelValidResponsePackage);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiBankPaymentValidateBicGet', function() {
        it('should call apiBankPaymentValidateBicGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiBankPaymentValidateBicGet call and complete the assertions
          /*
          var opts = {};

          instance.apiBankPaymentValidateBicGet(apiVersion, authorization, fMessageId, fOrigin, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FinacApi.ValidateBicViewModelValidResponsePackage);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiBankPaymentValidateInstantBicGet', function() {
        it('should call apiBankPaymentValidateInstantBicGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiBankPaymentValidateInstantBicGet call and complete the assertions
          /*
          var opts = {};

          instance.apiBankPaymentValidateInstantBicGet(apiVersion, authorization, fMessageId, fOrigin, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FinacApi.ValidateBicViewModelValidResponsePackage);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
