/*
 * Finac API
 * <b>Version Notes:- <br/>• All amounts fields in requests and responses have been changed from decimal to int64(cents). This means that 10.00 in version 1, is 1000 in version 2.<br/>• ThreeDS endpoints have been added to this version. These will replace the KBA endpoints from version 1.</br>• AccountId endpoint has changed HTTP verb from GET to POST, furthermore additional cardholder details need to be provided as part of the HTTP body.</b>
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FinacApi);
  }
}(this, function(expect, FinacApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FinacApi.ThreeDSApi();
  });

  describe('(package)', function() {
    describe('ThreeDSApi', function() {
      describe('apiThreeDSIdGet', function() {
        it('should call apiThreeDSIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiThreeDSIdGet call and complete the assertions
          /*

          instance.apiThreeDSIdGet(id, apiVersion, authorization, fMessageId, fOrigin, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FinacApi.EnrollmentDetailsThreeDSViewModelValidResponsePackage);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiThreeDSIdSecurityDetailsPatch', function() {
        it('should call apiThreeDSIdSecurityDetailsPatch successfully', function(done) {
          // TODO: uncomment, update parameter values for apiThreeDSIdSecurityDetailsPatch call and complete the assertions
          /*
          var opts = {};

          instance.apiThreeDSIdSecurityDetailsPatch(id, apiVersion, authorization, fMessageId, fOrigin, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FinacApi.UpdateSecurityDetailsThreeDSViewModelValidResponsePackage);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiThreeDSIdValidatePost', function() {
        it('should call apiThreeDSIdValidatePost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiThreeDSIdValidatePost call and complete the assertions
          /*
          var opts = {};

          instance.apiThreeDSIdValidatePost(id, apiVersion, authorization, fMessageId, fOrigin, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FinacApi.ValidateSecurityAnswerThreeDSViewModelValidResponsePackage);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
